
export type Destination = {
  slug: string;
  title: string;
  country: 'Tanzania' | 'Kenya';
  description: string;
  longDescription: string;
  image: string;
  imageHint: string;
  isPrime?: boolean;
};

export const destinations: Destination[] = [
  {
    slug: 'serengeti-national-park',
    title: 'Serengeti National Park',
    country: 'Tanzania',
    description: 'Home to the Great Migration, an endless expanse of iconic African savanna.',
    longDescription: 'The Serengeti is the Africa of your dreams. Famous for the annual Great Migration, where millions of wildebeest and zebra thunder across the plains in search of fresh grazing. Its vast, sun-kissed landscapes are dotted with acacia trees and roaming herds of lion, leopard, elephant, and buffalo. It is the ultimate safari destination, offering unparalleled wildlife viewing year-round.',
    image: 'https://images.unsplash.com/photo-1583313499482-a3f36c64441e?q=80&w=2070&auto=format&fit=crop',
    imageHint: 'serengeti plains',
    isPrime: true,
  },
  {
    slug: 'maasai-mara-national-reserve',
    title: 'Maasai Mara National Reserve',
    country: 'Kenya',
    description: 'Kenya\'s crown jewel, offering breathtaking landscapes and abundant wildlife.',
    longDescription: 'Adjoining the Serengeti, the Maasai Mara is world-renowned for its exceptional population of big cats and as the northern stage for the Great Migration. The dramatic river crossings of the Mara River are a spectacle of nature. Beyond the migration, its rolling grasslands and acacia-studded plains are teeming with life, offering a classic safari experience.',
    image: 'https://images.unsplash.com/photo-1534437431454-16291a105963?q=80&w=2070&auto=format&fit=crop',
    imageHint: 'maasai mara elephants',
    isPrime: true,
  },
  {
    slug: 'ngorongoro-crater',
    title: 'Ngorongoro Crater',
    country: 'Tanzania',
    description: 'A self-contained world of wildlife within a massive volcanic caldera.',
    longDescription: 'The Ngorongoro Crater is a geological marvel and a UNESCO World Heritage Site. This giant collapsed volcano forms a natural enclosure that hosts one of the densest concentrations of wildlife in Africa. It is one of the best places to see the Big Five, including the rare black rhino, all within a single day\'s game drive on the crater floor.',
    image: 'https://images.unsplash.com/photo-1549488344-cbb6c34cf08b?q=80&w=1974&auto=format&fit=crop',
    imageHint: 'ngorongoro wildlife',
    isPrime: true,
  },
  {
    slug: 'amboseli-national-park',
    title: 'Amboseli National Park',
    country: 'Kenya',
    description: 'Famous for its large elephant herds against the backdrop of Mount Kilimanjaro.',
    longDescription: 'Amboseli offers one of the most iconic images of Africa: vast herds of elephants with the snow-capped peak of Mount Kilimanjaro rising from the plains. The park\'s dry, dusty plains are fed by underground springs, creating lush wetlands that attract a rich diversity of wildlife, including lions, cheetahs, and a plethora of bird species.',
    image: 'https://images.unsplash.com/photo-1516426122078-c23e763199c1?q=80&w=2070&auto=format&fit=crop',
    imageHint: 'amboseli elephants',
    isPrime: true,
  },
  {
    slug: 'zanzibar-archipelago',
    title: 'Zanzibar Archipelago',
    country: 'Tanzania',
    description: 'Pristine beaches, spice-scented history, and turquoise waters.',
    longDescription: 'The perfect post-safari retreat, Zanzibar is an archipelago of idyllic islands. Explore the narrow, winding streets of historic Stone Town, a UNESCO World Heritage site, relax on palm-fringed white sand beaches, and dive or snorkel in the crystal-clear waters of the Indian Ocean, rich with coral reefs and marine life.',
    image: 'https://images.unsplash.com/photo-1577783932827-c139c1cc2269?q=80&w=2070&auto=format&fit=crop',
    imageHint: 'zanzibar beach',
    isPrime: true,
  },
  {
    slug: 'tarangire-national-park',
    title: 'Tarangire National Park',
    country: 'Tanzania',
    description: 'A landscape of baobab trees and home to massive elephant herds in the dry season.',
    longDescription: 'Tarangire is a land of giants, characterized by its ancient baobab trees and large elephant populations. During the dry season, the Tarangire River becomes a vital lifeline, attracting an incredible concentration of wildlife. It\'s a superb park for birdwatching and offers a more secluded safari experience.',
    image: 'https://images.unsplash.com/photo-1621383742442-595353380c55?q=80&w=2070&auto=format&fit=crop',
    imageHint: 'tarangire baobab',
  },
  {
    slug: 'lake-nakuru-national-park',
    title: 'Lake Nakuru National Park',
    country: 'Kenya',
    description: 'A soda lake famous for its vast flocks of flamingos and rhino sanctuary.',
    longDescription: 'Lake Nakuru is a vibrant sea of pink, thanks to the thousands of flamingos that feed on the algae in its alkaline waters. The park is a dedicated rhino sanctuary, making it one of the best places in Kenya to see both black and white rhinos. The surrounding acacia woodland is also home to leopards, lions, and giraffes.',
    image: 'https://images.unsplash.com/photo-1535182475949-a417855b5bae?q=80&w=1974&auto=format&fit=crop',
    imageHint: 'lake nakuru flamingos',
  },
  {
    slug: 'ruaha-national-park',
    title: 'Ruaha National Park',
    country: 'Tanzania',
    description: 'Tanzania\'s largest park, a remote and rugged wilderness with a wild, untouched feel.',
    longDescription: 'For those seeking a true off-the-beaten-path adventure, Ruaha is the perfect destination. Its dramatic landscapes are home to a huge diversity of wildlife, including 10% of the world\'s lion population and one of East Africa\'s largest elephant herds. The park\'s remoteness ensures an exclusive and authentic safari experience.',
    image: 'https://images.unsplash.com/photo-1673894348398-4a413347c0cf?q=80&w=2070&auto=format&fit=crop',
    imageHint: 'ruaha river',
  },
  {
    slug: 'samburu-national-reserve',
    title: 'Samburu National Reserve',
    country: 'Kenya',
    description: 'An arid, rugged landscape home to unique wildlife known as the Samburu Special Five.',
    longDescription: 'Samburu offers a starkly beautiful, semi-arid landscape. It is here you can find the "Samburu Special Five": the Grevy\'s zebra, the reticulated giraffe, the Somali ostrich, the gerenuk, and the Beisa oryx. The Ewaso Ng\'iro river is a vital water source that attracts a plethora of other wildlife, including elephants and big cats.',
    image: 'https://images.unsplash.com/photo-1587588392184-ffe085024474?q=80&w=1974&auto=format&fit=crop',
    imageHint: 'samburu giraffe',
  },
  {
    slug: 'selous-game-reserve',
    title: 'Nyerere National Park (Selous)',
    country: 'Tanzania',
    description: 'One of the world\'s largest fauna reserves, offering boat safaris and walking tours.',
    longDescription: 'Formerly Selous Game Reserve, Nyerere National Park is a vast and wild area where the Rufiji River creates a network of lakes and channels. This allows for unique safari experiences, including boat safaris and guided walking tours, offering a different perspective on the African bush. It is home to large populations of wild dogs, hippos, and crocodiles.',
    image: 'https://images.unsplash.com/photo-1617937392683-97063e96642d?q=80&w=2070&auto=format&fit=crop',
    imageHint: 'tanzania wildlife',
  },
  {
    slug: 'tsavo-national-park',
    title: 'Tsavo National Park',
    country: 'Kenya',
    description: 'A vast wilderness of rocky landscapes, volcanic hills, and the legendary "red elephants".',
    longDescription: 'Comprising Tsavo East and Tsavo West, this is one of the largest parks in the world. It is known for its "red elephants" which dust themselves with the volcanic red soil, the man-eating lions of Tsavo legend, and the stunning Mzima Springs, where you can see hippos and crocodiles through an underwater viewing chamber.',
    image: 'https://images.unsplash.com/photo-1614332277864-7d216bdf32c2?q=80&w=2070&auto=format&fit=crop',
    imageHint: 'kenya elephants',
  },
  {
    slug: 'mahale-mountains-national-park',
    title: 'Mahale Mountains',
    country: 'Tanzania',
    description: 'Remote and beautiful, offering the best chimpanzee trekking in Africa.',
    longDescription: 'Set on the shores of the crystal-clear Lake Tanganyika, the Mahale Mountains are a remote paradise. The park\'s main attraction is the chance to track and observe a large population of habituated chimpanzees in their natural habitat. It\'s a magical experience combining forest trekking with lakeside relaxation.',
    image: 'https://images.unsplash.com/photo-1590494025147-3215b2258b44?q=80&w=1974&auto=format&fit=crop',
    imageHint: 'chimpanzee tanzania',
  },
  {
    slug: 'lake-manyara-national-park',
    title: 'Lake Manyara National Park',
    country: 'Tanzania',
    description: 'Known for its tree-climbing lions, flamingo-lined lake, and diverse habitats.',
    longDescription: 'Nestled at the base of the Great Rift Valley escarpment, Lake Manyara offers a microcosm of the Tanzanian safari experience. Its diverse habitats include groundwater forest, acacia woodland, and the soda lake itself. It is famous for its elusive tree-climbing lions and large troops of baboons.',
    image: 'https://images.unsplash.com/photo-1554922123-5b826b389456?q=80&w=2070&auto=format&fit=crop',
    imageHint: 'tanzania lions',
  },
  {
    slug: 'laikipia-plateau',
    title: 'Laikipia Plateau',
    country: 'Kenya',
    description: 'A collection of private and community conservancies at the forefront of conservation.',
    longDescription: 'Laikipia is a stunning success story of conservation, a patchwork of community and private wildlife reserves. It is a vital sanctuary for endangered species, including Grevy\'s zebra and black rhino. Laikipia offers a wide range of activities not typically found in national parks, such as night drives, horse riding, and camel treks.',
    image: 'https://images.unsplash.com/photo-1559815497-c2a4f470535c?q=80&w=2070&auto=format&fit=crop',
    imageHint: 'kenya rhino',
  },
  {
    slug: 'gombe-stream-national-park',
    title: 'Gombe Stream National Park',
    country: 'Tanzania',
    description: 'The site of Jane Goodall\'s pioneering chimpanzee research.',
    longDescription: 'Gombe is the smallest of Tanzania\'s national parks and the place where Jane Goodall began her groundbreaking research on chimpanzee behavior. Trekking through the steep forested slopes to find the chimps is an intimate and rewarding experience, offering a glimpse into the world she first revealed.',
    image: 'https://images.unsplash.com/photo-1591969853926-80a87673e449?q=80&w=2070&auto=format&fit=crop',
    imageHint: 'gombe chimpanzee',
  },
  {
    slug: 'diani-beach',
    title: 'Diani Beach',
    country: 'Kenya',
    description: 'Kenya\'s most stunning beach, with brilliant white sand and lush greenery.',
    longDescription: 'After an adventurous safari, Diani Beach is the perfect place to unwind. Its long stretch of powdery white sand is lapped by the warm Indian Ocean and fringed with palm trees. It offers a range of watersports, beautiful coral reefs for snorkeling, and a relaxed, welcoming atmosphere.',
    image: 'https://images.unsplash.com/photo-1540329029969-5c317f052516?q=80&w=2070&auto=format&fit=crop',
    imageHint: 'diani beach',
  },
  {
    slug: 'mount-kilimanjaro',
    title: 'Mount Kilimanjaro',
    country: 'Tanzania',
    description: 'Climb the highest freestanding mountain in the world, the legendary Mt. Kilimanjaro.',
    longDescription: 'Rising dramatically from the surrounding plains, Mount Kilimanjaro is Africa\'s highest peak. Climbing Kilimanjaro is a challenging but rewarding journey that takes you through five distinct climate zones, from rainforest to alpine desert and finally to the glacial summit. Reaching the "Roof of Africa" is an achievement of a lifetime.',
    image: 'https://images.unsplash.com/photo-1589928372449-3F447041a79f?q=80&w=2070&auto=format&fit=crop',
    imageHint: 'mount kilimanjaro',
  },
  {
    slug: 'katavi-national-park',
    title: 'Katavi National Park',
    country: 'Tanzania',
    description: 'A remote, wild, and untouched park offering a glimpse of Africa as it once was.',
    longDescription: 'Katavi is for the safari purist. In the dry season, the Katuma River shrinks to a trickle, forcing thousands of hippos and crocodiles into small pools. The sheer density of wildlife is breathtaking. With very few visitors, a safari in Katavi feels like a true exploration of a forgotten land.',
    image: 'https://images.unsplash.com/photo-1563897182245-095568be8841?q=80&w=1974&auto=format&fit=crop',
    imageHint: 'tanzania hippos',
  },
  {
    slug: 'mount-kenya-national-park',
    title: 'Mount Kenya National Park',
    country: 'Kenya',
    description: 'Africa\'s second-highest peak, offering a rugged landscape of peaks and glaciers.',
    longDescription: 'Mount Kenya is a stunning UNESCO World Heritage Site with a diverse range of ecosystems. While reaching the highest peaks is a technical climb, the surrounding park offers fantastic trekking opportunities through montane forests, bamboo zones, and moorlands, with the chance to see elephants, buffalo, and the rare bongo antelope.',
    image: 'https://images.unsplash.com/photo-1559595738-7f58b005e839?q=80&w=2069&auto=format&fit=crop',
    imageHint: 'mount kenya',
  },
];
